run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - typecheck
  disable:
    - errcheck

linters-settings:
  govet:
    shadow:
      strict: false
  staticcheck:
    checks:
      - all
      - -SA1019

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
